
Rust 中的错误处理是通过返回 `Result＜T, E＞` 类型的方式进行的. `Result＜T, E＞` 类型是 `Option＜T＞` 类型的升级版本, 同样定义于标准库中.

`Result＜T, E＞` 源码实现:

```rust
enum Result<T, E> {
	Ok(T),
	Err(T),
}
```

`Option＜T＞` 类型表示**值存在**的可能性, `Result＜T, E＞` 类型表示**错误**的可能性, 其中泛型 E 代表 Error.

```rust
// Not running?
fn code2_56() {
	let x: Result<i32, &str> = Ok(-3);
	assert_eq!(x.is_ok(), true);
	let x: Result<i32, &str> = Err("Some error message");
	assert_eq!(x.is_ok(), false);
}
```

可通过 `is_ok` 方法来判断是否为 `Ok(T)` 枚举值.

和 `Option＜T＞` 类似, 可以将 `Result＜T, E＞` 作为函数返回值. 如果返回类型是 `Result＜T, E＞`, 那么开发者就不得不处理正常和错误这两种情况.

Rust 2015 中, main 函数并不能返回 `Result＜T, E＞`. 但实际开发中, 二进制可执行库也需要返回错误, 比如, 读取文件的时候发生了错误, 这时需要正常退出程序. Rust 2018版本中, 允许main函数返回 `Result＜T, E＞`.

```rust
// Not running?
use std::fs::File;
fn main() -> Result<(), std::io::Error> {
	let f = File::open("bar.txt")?;
	Ok(())
}
```

后面跟随的问号操作符(`?`)是一个错误处理的语法糖, 它会自动在出现错误的情况下返回 `std::io::Error`. 这样就可以在程序发生错误时自动返回错误码, 并在退出程序时打印相关的错误信息, 方便调试, 而不需要开发者手动处理错误.